# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  validate-build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ubuntu1804-base.json
      - run:
          name: Build AMI
          command: packer build ubuntu1804-base.json


workflows:
  version: 2
  validate_build_test:
    jobs:
      - validate-build
